name: Functional Tests Workflow

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - dev
      - main

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello world
        run: echo "Welcome to the Github Actions workshop !"
  
  unit-test:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set permissions for functional-test.sh
      run: chmod +x functional-test.sh

    - name: Run functional tests
      run: ./functional-test.sh

    - name: Upload test outputs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: function-tests_outputs
        path: ./functional-test.sh
