name: Tests

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    branches:
      - dev
      - main

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello world
        run: echo "Welcome to the Github Actions workshop !"

  unit-test:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run unit tests
        run: |
          make tests > test-output.txt

      - name: Run coverage
        run: |
          make coverage > coverage-output.txt

      - name: Upload coverage outputs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage_outputs
          path: coverage-output.txt

  functional-test:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run functional tests
        run: |
          make functional-tests > functional-test.sh

      - name: Upload functional tests outputs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: function-tests_outputs
          path: functional-tests-output.txt
